### ISSUE TITLE
Private State still exposed to the client

### ISSUE THREAD

**Issue by minyou9** [nuxt-community/universal-storage-module#127]
I am following the docs from https://github.com/nuxt-community/universal-storage-module

I tried to set this: `$storage.setState("_password", "alpha1") ` in the async fetch(). When I inspect the client browser console by using this `$nuxt.$store.$storage._state`, I can see my private state there

I am not sure if this behavior is expected to work like this?

**Comment by pi0** [comment]
Hi @minyou9. It is little bit confusing for being called _private_ in the docs. Private state is omitted from page payload only. For server-only credentials, you can use [privateRuntimeConfig](https://nuxtjs.org/guide/runtime-config/#runtime-config-213)

**Comment by minyou9** [comment]
@pi0 thank you for verify that 🙏
