### ISSUE TITLE
Issue with using this package with nuxt-ssr-cache

### ISSUE THREAD

**Issue by jollemannen** [nuxt-community/universal-storage-module#145]
Hi!

I would love to use this package but i have discovered a conflict.

If i use this package with nuxt-ssr-cache i receive the following error $storage is undefined and cannot use this package. It seems that there is a conflict between the two packages.

Is there a way to fix this, if so could you guys help me?

Have a nice day:)

Regards Joel

**Comment by farzadso** [comment]
I will try my best to look into it the upcoming week. In the meanwhile, @pi0 do you have any ideas?
