### ISSUE TITLE
Unable to set expiration date for cookie

### ISSUE THREAD

**Issue by bilaleren** [nuxt-community/universal-storage-module#151]
**I think Nuxt converts the date object to string.**

My storage options
<img width="213" alt="Ekran Resmi 2020-10-29 23 04 11" src="https://user-images.githubusercontent.com/48865064/97626730-5405f000-1a3b-11eb-8b1f-f62e0c50dfeb.png">

My date object
<img width="360" alt="Ekran Resmi 2020-10-29 23 04 26" src="https://user-images.githubusercontent.com/48865064/97626752-5d8f5800-1a3b-11eb-922c-8ff067fc6137.png">

Console error
<img width="391" alt="Ekran Resmi 2020-10-29 23 04 54" src="https://user-images.githubusercontent.com/48865064/97626769-66802980-1a3b-11eb-8a56-148dbc6255dc.png">

**Comment by farzadso** [comment]
@bilaleren I would appreciate it if you could create a code sandbox so I can check it in more detail.

**Comment by bilaleren** [comment]
> @bilaleren I would appreciate it if you could create a code sandbox so I can check it in more detail.

Sandbox https://codesandbox.io/s/nuxt-storage-nemy4?file=/pages/index.vue

**Comment by farzadso** [comment]
@bilaleren This issue should be fixed in [v0.5.6](https://github.com/nuxt-community/universal-storage-module/releases/tag/v0.5.6).

Please re-open if the issue exists.
