### ISSUE TITLE
Missing CircleCI Config

### ISSUE THREAD

**Issue by farzadso** [nuxt-community/universal-storage-module#178]
Seems like the circleci config was removed here:

https://app.circleci.com/pipelines/github/nuxt-community/universal-storage-module

Was this intentional @pi0?

**Comment by pi0** [comment]
Hi farzad. Yes we already migrated all repos using github actions. Example: https://github.com/nuxt/http/blob/master/.github/workflows/ci.yml

**Comment by farzadso** [comment]
Thanks, Pooya.

Since we're using an outdated badge, do you recommend a certain badge for the new config?

![image](https://user-images.githubusercontent.com/19854715/114273646-2aacaf80-9a30-11eb-89a9-7ad508b28a89.png)

**Comment by farzadso** [comment]
I added the badge above. Please re-open if there are any considerations required bro.
