### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by sebmor** [nuxt-community/universal-storage-module#29]
This is not an issue, but I was just wondering.
It seems to have become a convention to name "official" nuxt packages @nuxtjs/{{package}} ie:
@nuxtjs/auth, @nuxtjs/pwa, @nuxtjs/router-extras, .. almost all of them.

Is there a particular reason why you didn't follow this "convention"?

**Comment by farzadso** [comment]
Hi @sebmor 

The reason is that this module was written for our company-specific needs at first and was then moved into the nuxt-community. 

Do you have any comments on this issue @pi0 ?

**Comment by kevinmarrec** [comment]
Hey @farzadso , i'm gonna see with Nuxt team if it's relevant to make it `@nuxtjs`, IMO it is but just need aprovement of other core team members.

Could you provide me npm permissions so I can publish 0.3.0 with TypeScript type definitions ?

**Comment by farzadso** [comment]
@kevinmarrec Done Kevin. Any chance I could see the changes before we publish them?

**Comment by kevinmarrec** [comment]
@farzadso You can check my last commits, sorry I should have make PR 🤦. I can rollback if needeed, give me your green light and I'll only publish if everything is ok 👍

**Comment by farzadso** [comment]
@kevinmarrec It's all good. Thanks for adding the TS defs. ❇️

**Comment by pi0** [comment]
New release published as [@nuxtjs/universal-storage](https://www.npmjs.com/package/@nuxtjs/universal-storage)
