### ISSUE TITLE
Full synchronise on start is not part of the 0.4.0 release

### ISSUE THREAD

**Issue by husayt** [nuxt-community/universal-storage-module#61]
Readme says "Since version 0.4.0 this module allows full state synchronisation with cookies, localstorage and initialstate as a default value." 

However, that code has been merged after the 0.4.0 release and not available yet. Can you please make another release with the latest.

**Comment by husayt** [comment]
@pi0 @farzadso am i missing something? or version published on NPM is different than what is released here.

**Comment by husayt** [comment]
@pi0 this can be closed with 0.5.0 release

**Comment by farzadso** [comment]
I'm so sorry for seeing this issue so late @husayt .

The version hadn't been published.
