### ISSUE TITLE
Initial state as a function

### ISSUE THREAD

**Issue by husayt** [nuxt-community/universal-storage-module#65]
It might be very useful set an initial state dynamically for each visitor to take into account location or language. 

So it will be great if initial state could also be defined as a function.

**Comment by farzadso** [comment]
@husayt Could you explain a bit more what you're trying to achieve? 

Can't you move this logic to `nuxtServerInit`?

**Comment by husayt** [comment]
Yes, indeed I just moved that logic to a plugin
