### ISSUE TITLE
How to import configuration

### ISSUE THREAD

**Issue by liseipi** [nuxt-community/universal-storage-module#91]
in NUXT nuxt.config.js
storage: '@/plugins/storage',

plugins/storage.js file
```
export default {
  vuex: {
    namespace: 'storage'
  },
  localStorage: {
    prefix: 'storage.'
  }
}
```

**This does not work, how to configure it correctly?**

**Comment by farzadso** [comment]
What do you mean by `This does not work` ? 

Does it produce an error? Which part of it doesn't work?

Can you provide a repo which contains the problem?

**Comment by liseipi** [comment]
> 你是什么意思`This does not work`？
> 
> 它会产生错误吗？哪一部分不起作用？
> 
> 您可以提供包含该问题的回购吗？



> What do you mean by `This does not work` ?
> 
> Does it produce an error? Which part of it doesn't work?
> 
> Can you provide a repo which contains the problem?

I want to import the configuration file in the nuxt.config.js file and found that it does not work
